apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: l1w5st3i7-java-springboot
  janus-idp.io/tekton: l1w5st3i7-java-springboot
  backstage.io/kubernetes-id: l1w5st3i7-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: l1w5st3i7-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
